---
# vars file for roles/dev
packages:
    - docker
    - docker-compose
    - git
    - jq
    - vim
    - nmap
    - openssl
    - tree
    - wget
    - tmux

gitconfig:
    - { name: "user.name", value: "ymmmtym"}
    - { name: "user.email", value: "26668352+ymmmtym@users.noreply.github.com"}
    - { name: "core.editor", value: 'vim -c "set fenc=utf-8"'}
    - { name: "color.diff", value: auto}
    - { name: "color.status", value: auto}
    - { name: "color.branch", value: auto}
    - { name: "alias.cm", value: "commit -m"}
    - { name: "alias.pom", value: "push origin master"}
    - { name: "alias.su", value: "submodule update"}
    - { name: "alias.rh", value: "reset --hard HEAD^"}

dein:
    install_script: 'dein_installer.sh'
    install_dir: '~/.vim/bundles'
    rc_dir: '~/.vim/rc'
    toml: 'dein.toml'
    lazy_toml: 'dein_lazy.toml'