---
- hosts: all
  roles:
    - role: homebrew
      when: ansible_os_family == "Darwin"
      tags: homebrew

- hosts: dev
  roles:
    - role: dev
      when: ansible_os_family != "Windows"
      tags: dev

- hosts: web_server
  roles:
    - role: web_server
      tags: web_server
