---
# tasks file for roles/growi
- name: clone growi repository
  git:
    repo: 'https://github.com/ymmmtym/growi-docker-compose.git'
    dest: growi
    clone: yes
    update: yes
  
#   - name: copy override yml
#     shell: cp examples/https-portal/docker-compose.override.yml .

- name: docker compose up
  docker_compose:
    project_src: growi
    state: present
  become: yes