all:
    children:
        dev:
            hosts: localhost
            vars:
                ansible_connection: local
                ansible_python_interpreter: /usr/bin/python3
        web_server:
            children:
                growi:
                    hosts: ubuntu01
                keywoo:
                    hosts: centos01
