all:
    children:
        local:
            hosts: localhost
            vars:
                ansible_connection: local
        web_server:
            children:
                growi:
                    hosts: ubuntu01

                wikijs:
                    hosts: centos01
