---
# tasks file for roles/web_server
- name: Include Redhat task
  include: packages_redhat.yml
  tags: [ packages, redhat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian task
  include: packages_debian.yml
  tags: [ packages, debian ]
  when: ansible_os_family == "Debian"