---
# tasks file for roles/web_server
- name: Include Redhat Docker task
  include_role:
    name: dev
    tasks_from: docker_redhat.yml
  tags: [ docker, packages, redtat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian Docker task
  include_role:
    name: dev
    tasks_from: docker_debian.yml
  tags: [ docker, packages, debian ]
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version | float < 20.04

- name: Include Debian Docker task only Ubuntu20.04
  include_role:
    name: dev
    tasks_from: docker_ubuntu20.04.yml
  tags: [ docker, packages, debian ]
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version | float == 20.04