---
# tasks file for roles/web_server
- name: Install packages
  block:
    - name: Include Redhat packages task
      include: packages_redhat.yml
      tags: [ redhat ]
      when: ansible_os_family == "RedHat"
    - name: Include Debian packages task
      include: packages_debian.yml
      tags: [ debian ]
      when: ansible_os_family == "Debian"
  tags: [ packages ]

- name: Insatall Docker
  block:
    - name: check docker version
      command: docker version -f \{\{.Server.Version\}\}
      changed_when: false
      ignore_errors: yes
      register: docker_version

    - name: check docker compose version
      command: docker-compose version --short
      changed_when: false
      ignore_errors: yes
      register: docker_compose_version

    - name: Include Redhat Docker task
      include_role:
        name: dev
        tasks_from: docker_redhat.yml
      tags: [ redhat ]
      when:
        - ansible_os_family == "RedHat"

    - name: Include Debian Docker task
      include_role:
        name: dev
        tasks_from: docker_debian.yml
      tags: [ debian ]
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution_version | float < 20.04

    - name: Include Debian Docker task only Ubuntu20.04
      include_role:
        name: dev
        tasks_from: docker_ubuntu20.04.yml
      tags: [ debian ]
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution_version | float == 20.04
  tags: [ docker, packages ]

- name: Upgrade pip
  pip:
    name: pip
    state: latest # noqa 403
  become: yes

- name: Install docker in pip
  pip:
    name: '{{ item }}'
    state: present
  become: yes
  loop:
    - docker
    - docker-compose