---
# tasks file for roles/web_server
- name: Include Redhat task
  include: packages_redhat.yml
  tags: [ packages, redhat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian task
  include: packages_debian.yml
  tags: [ packages, debian ]
  when: ansible_os_family == "Debian"

- name: Include Redhat Docker task
  include: docker_redhat.yml
  tags: [ docker, packages, redtat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian Docker task
  include: docker_debian.yml
  tags: [ docker, packages, debian ]
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version | float < 20.04

- name: Include Debian Docker task
  include: docker_ubuntu20.04.yml
  tags: [ docker, packages, debian ]
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version | float == 20.04