- name: Install common packages
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ packages }}'

- name: Install python-pip
  yum:
    name: '{{ item }}'
    state: present
    enablerepo: epel
  become: yes
  loop: [ python-pip, python-devel, gcc ]