- name: Install common packages
  dnf:
    name: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  loop: '{{ packages }}'

- name: Install epel-release
  dnf:
    name: epel-release
    state: present
  become: yes
  when: ansible_distribution_version | float < 8

- name: Install python-pip
  dnf:
    name: '{{ item }}'
    state: present
    enablerepo: epel
  become: yes
  loop:
    - python-devel
    - python-pip
  when: ansible_distribution_version | float < 8
