---
# tasks file for roles/homebrew
- name: Homebrew tap
  homebrew_tap:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ brew_taps }}'

- name: Install Homebrew Cask Packages
  homebrew_cask:
    name: '{{ item }}'
    state: present
    install_options: 'appdir=/Applications'
    accept_external_apps: yes
  loop: '{{ brew_cask_apps }}'

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install Homebrew Packages
  homebrew:
    name: '{{ item }}'
    state: present
  loop: '{{ brew_packages }}'