---
# tasks file for roles
- name: include vars
  include_vars:
    dir: vars

- name: copy files to home dir
  copy:
    src: '{{ item }}'
    dest: '~'
  with_fileglob: "files/homedir/.*"

- block:
  - name: set gitconfig global secret
    git_config:
      name: '{{ item.name }}'
      scope: global
      value: '{{ item.value }}'
    with_items: '{{ gitconfig_secret }}'

  - name: set gitconfig global
    git_config:
      name: '{{ item.name }}'
      scope: global
      value: '{{ item.value }}'
    with_items: '{{ gitconfig }}'
