---
# tasks file for roles
- name: include vars
  include_vars:
    dir: vars
  tags: always

- name: Include dotfiles task
  include: dotfiles.yml
  tags: dotfiles

- name: Include git task
  include: git.yml
  tags: git

- name: Include dein task
  include: dein.yml
  tags: dein