---
# tasks file for roles
- name: include vars
  include_vars:
    dir: vars
  tags: always

- name: copy files to home dir
  copy:
    src: '{{ item }}'
    dest: '~'
  with_fileglob: "homedir/.*"

- name: Include git task
  include: git.yml
  tags: git

- name: Include vim task
  include: vim.yml
  tags: vim