- name: copy config file
  copy:
    src: 'fish/config.fish'
    dest: '~/.config/fish/'

- name: register fish path
  command: 'which fish'
  register: fish_path
  changed_when: False
  check_mode: no

- name: apply fish to user shell
  user:
    name: '{{ ansible_user }}'
    shell: '{{ fish_path.stdout }}'
  when: ansible_user_shell != fish_path.stdout
  become: yes
