- name: set gitconfig global secret
  git_config:
    name: '{{ item.name }}'
    scope: global
    value: '{{ item.value }}'
  with_items: '{{ gitconfig_secret }}'

- name: set gitconfig global
  git_config:
    name: '{{ item.name }}'
    scope: global
    value: '{{ item.value }}'
  with_items: '{{ gitconfig }}'