---
# tasks file for roles
- name: Include Redhat packages task
  include: packages_redhat.yml
  tags: [ packages, redhat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian packages task
  include: packages_debian.yml
  tags: [ packages, debian ]
  when: ansible_os_family == "Debian"

- name: Include rbenv task
  include: rbenv.yml
  tags: rbenv
  when: ansible_os_family in ("RedHat","Debian")

- name: Include dotfiles task
  include: dotfiles.yml
  tags: dotfiles

- name: Include fish task
  include: fish.yml
  tags: fish

- name: Include git task
  include: git.yml
  tags: git

- name: Include dein task
  include: dein.yml
  tags: dein