---
# tasks file for roles
- name: include vars
  include_vars:
    dir: vars
  tags: always

- name: Include Redhat task
  include: redhat.yml
  tags: redhat
  when: ansible_os_family == "RedHat"

- name: Include Debian task
  include: debian.yml
  tags: debian
  when: ansible_os_family == "Debian"

- name: Include dotfiles task
  include: dotfiles.yml
  tags: dotfiles

- name: Include fish task
  include: fish.yml
  tags: fish

- name: Include git task
  include: git.yml
  tags: git

- name: Include dein task
  include: dein.yml
  tags: dein