---
# tasks file for roles
- name: Include Redhat packages task
  include: packages_redhat.yml
  tags: [ packages, redhat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian packages task
  include: packages_debian.yml
  tags: [ packages, debian ]
  when: ansible_os_family == "Debian"

- name: Include Redhat Docker task
  include: docker_redhat.yml
  tags: [ docker, packages, redtat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian Docker task
  include: docker_debian.yml
  tags: [ docker, packages, debian ]
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version | float < 20.04

- name: Include Debian Docker task only Ubuntu20.04
  include: docker_ubuntu20.04.yml
  tags: [ docker, packages, debian ]
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version | float == 20.04

- name: Include rbenv task
  include: rbenv.yml
  when: ansible_os_family in ("RedHat","Debian")
  tags: rbenv

- name: Include dotfiles task
  include: dotfiles.yml
  tags: dotfiles

- name: Include git task
  include: git.yml
  tags: git

- name: Include dein task
  include: dein.yml
  tags: dein

- name: Include fish task
  include: fish.yml
  tags: fish