---
# tasks file for roles
- name: Install packages
  block:
    - name: Include Redhat packages task
      include: packages_redhat.yml
      tags: [ redhat ]
      when: ansible_os_family == "RedHat"
    - name: Include Debian packages task
      include: packages_debian.yml
      tags: [ debian ]
      when: ansible_os_family == "Debian"

  tags: [ packages ]


- name: Insatall Docker
  block:
    - name: check docker version
      command: docker version -f \{\{.Server.Version\}\}
      changed_when: false
      ignore_errors: yes
      register: docker_version

    - name: check docker compose version
      command: docker-compose version --short
      changed_when: false
      ignore_errors: yes
      register: docker_compose_version

    - name: Include Redhat Docker task
      include: docker_redhat.yml
      tags: [ redhat ]
      when:
        - ansible_os_family == "RedHat"
        - (docker_version.stdout | float < docker.version) or (docker_compose_version.stdout | float < docker_compose.version)

    - name: Include Debian Docker task
      include: docker_debian.yml
      tags: [ debian ]
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution_version | float < 20.04
        - (docker_version.stdout | float < docker.version) or (docker_compose_version.stdout | float < docker_compose.version)

    - name: Include Debian Docker task only Ubuntu20.04
      include: docker_ubuntu20.04.yml
      tags: [ debian ]
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution_version | float == 20.04
        - (docker_version.stdout | float < docker.version) or (docker_compose_version.stdout | float < docker_compose.version)

  tags: [ docker, packages ]

- name: Include rbenv task
  include: rbenv.yml
  when: ansible_os_family in ("RedHat","Debian")
  tags: rbenv

- name: Include dotfiles task
  include: dotfiles.yml
  tags: dotfiles

- name: Include git task
  include: git.yml
  tags: git

- name: Include dein task
  include: dein.yml
  tags: dein

- name: Include fish task
  include: fish.yml
  tags: fish