- name: Install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: Install common packages
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items: ['{{ packages }}']
