- name: Install fish for Centos8
  get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo
    dest: /etc/yum.repos.d/
  become: yes
  when:
    - ansible_distribution_major_version | float == 8

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: Install common packages
  become: yes
  yum:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: '{{ packages }}'