- name: remove lock files
  become: yes
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /var/lib/apt/lists/lock
    - /var/lib/dpkg/lock

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Add apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-2"
  become: yes

- name: Install common packages
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items: ['{{ packages }}']
