- name: Install common packages
  become: yes
  apt: 
    name: '{{ item }}'
    state: present
  with_items: ['{{ packages }}']

- name: Add apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-2"
  become: yes

- name: Install fish package
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - fish