- name: Install common packages
  become: yes
  yum: 
    name: '{{ item }}'
    state: present
  with_items: ['{{ packages }}']

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  become: yes
  
- name: Install fish package
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - fish