# - name: hack to resolve Problem with MergeList Issue
#   sudo: true
#   command: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Add apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-2"
  become: yes

- name: Install common packages
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items: ['{{ packages }}']
