- name: remove lock files
  become: yes
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /var/lib/apt/lists/*
    - /var/lib/dpkg/*

- name: Add apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-2"
  become: yes

- name: Install common packages
  become: yes
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items: ['{{ packages }}']
