- name: Run the equivalent of "yum update" as a separate step
  yum:
    update_cache: yes
  become: yes

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: Install common packages
  become: yes
  yum:
    name: '{{ item }}'
    state: present
  with_items: ['{{ packages }}']
