---
- name: Mac Setup
  hosts: local
  vars:
    brew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-versions
      - homebrew/cask-fonts
    brew_cask_apps:
      - docker
      - google-chrome
      - google-japanese-ime
      - visual-studio-code
      - slack
    brew_packages:
      - docker-compose
      - docker-machine
      - git
      - git-lfs
      - jq
      - vim
      - nmap
      - openssl
      - ssh-copy-id
      - tree
      - wget
      - zsh
      - zsh-syntax-highlighting
 
  tasks:
    - name: Homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_taps }}"
 
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_apps }}"
 
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
 
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"