name: Ansible
on: [push, pull_request]

jobs:
  ansible_lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "site.yml"
  
  homebrew:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: pip3 install -r requirements.txt

    - name: Homebrew role
      run: ansible-playbook site.yml -t homebrew