name: Ansible
on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "site.yml"

  ansible-playbook:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [macOS-latest, ubuntu-latest]
    env:
      PYTHON_VERSION: 3.7

    steps:
      - uses: actions/checkout@v2

      - name: spctl
        run: sudo /usr/sbin/spctl --master-disable
        if: runner.os == 'macOS'

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install requirements
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Run ansible playbook to "dev" inventory hosts
        run: ansible-playbook site.yml -l dev -vvv